apiVersion: v1
kind: Namespace
metadata:
  name: whoami-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.11.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami-app
  labels:
    app: whoami
spec:
  selector:
    app: whoami
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: whoami-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
    external-dns.alpha.kubernetes.io/hostname: whoami.gytis.place
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  tls:
    - hosts:
      - whoami.gytis.place
  rules:
    - host: whoami.gytis.place
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
